name: nightly-workflow

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build Java application 
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
        with:
          ref: develop
      
      - name: Set up java version
        uses: actions/setup-java@v1
        with:
          java-version: 15
      
      - name: Run Unitary tests
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test

      - name: Run Rest tests
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test

      - name: Run Selenium tests
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test

      - name: Generate artifact
        run: mvn -B package -DskipTests

      - name: Upload jar for next job
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
          retention-days: 1

  publish_in_dockerhub:
    name: Publish in DockerHub
    runs-on: ubuntu-20.04
    needs: [build] 
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Download Jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target

      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d.%H%M%S')
        id: project

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/books:dev-${{ steps.project.outputs.tag }} .
      
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/books:dev-${{ steps.project.outputs.tag }}
      